export enum EnumStatusCode {
  SUCCESS = "SUCCESS",
  BAD_REQUEST = "BAD_REQUEST",
  SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG",
  UNAUTHORIZED = "UNAUTHORIZED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  EXISTS_ALREADY = "EXISTS_ALREADY",
}
