export enum EnumStatusCode {
  BAD_REQUEST = "BAD_REQUEST",
  SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG",
  UNAUTHORIZED = "UNAUTHORIZED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  EXISTS_ALREADY = "EXISTS_ALREADY",
  CREATED_SUCCESSFULLY = "CREATED_SUCCESSFULLY",
  UPDATED_SUCCESSFULLY = "UPDATED_SUCCESSFULLY",
  NOT_FOUND = "NOT_FOUND",
}
